name: Deploy to Staging

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets._SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
  GA_NODE_VERSION: ${{ secrets.GA_NODE_VERSION }}
  IMAGE_NAME: ghcr.io/asvgay/the-rhapsodies

on:
  push:
    branches:
      - staging
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-migrations-staging:
    runs-on: ubuntu-24.04
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to hosted Supabase
        run: supabase link --project-ref ${{ secrets._SUPABASE_PROJECT_ID }}

      - name: Push local migrations to hosted Supabase
        run: supabase db push

      - name: Push local functions to hosted Supabase
        run: supabase functions deploy

  build-and-push-staging-image:
    needs: deploy-migrations-staging
    runs-on: ubuntu-latest
    environment: staging

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=staging
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
