name: Deploy to Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets._SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
  GA_NODE_VERSION: ${{ secrets.GA_NODE_VERSION }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-migrations-production:
    runs-on: ubuntu-24.04
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Link to hosted Supabase
        run: supabase link --project-ref ${{ secrets._SUPABASE_PROJECT_ID }}
      - name: Push local migrations to hosted Supabase
        run: supabase db push
      - name: Push local functions to hosted Supabase
        run: supabase functions deploy
  deploy-vercel-production:
    needs: deploy-migrations-production
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.GA_NODE_VERSION }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
